- hosts: all
  remote_user: root
  vars:
      wiki_name: "{{ wiki_name_var }}"
      domain_name: "{{ domain_name_var }}"
      admin_user: "{{ admin_user_var }}"
      admin_pwd:  "{{ admin_pwd_var }}"
      mw_version: 1.31.0

  tasks: 
    - name: Install required debs
      apt: 
        name: "{{ item }}"
        state: present
      with_items: 
        - php7.0-fpm
        - php7.0-mbstring
        - php7.0-mcrypt
        - php7.0-mysql
        - php7.0-zip
        - php7.0-xml
        - php7.0-gd
        - php7.0-curl
        - python-mysqldb
        - apache2
        - mariadb-server
        - mariadb-client
        - php-apcu
        - php-intl
        - imagemagick
        - inkscape
        - php-gd
        - php-cli
        - git
        - libapache2-mod-php7.0

    - name: Download mediawiki
      get_url:
          url: https://releases.wikimedia.org/mediawiki/1.31/mediawiki-1.31.0.tar.gz
          dest: /tmp/mediawiki.tgz

    - name: Create mediawiki Directory
      file:
          path: /var/lib/mediawiki
          state: directory


    - name: Extract mediawiki tar ball
      unarchive:
          src:  /tmp/mediawiki.tgz
          dest: /var/lib/mediawiki
          remote_src: yes
          owner: www-data
          group: www-data

    - name: Rename media wiki root dir
      command: creates=/var/lib/mediawiki/wiki mv "/var/lib/mediawiki/mediawiki-{{ mw_version }}" /var/lib/mediawiki/wiki

    - name: Create DataBase User
      mysql_user:
          name: "{{ admin_user }}"
          password: "{{ admin_pwd }}"
          priv: "*.*:ALL"
          state: present

    - name: Create DataBase
      mysql_db:
          name: mwdb
          encoding: utf8
          state: present

    - name: Remove html dir
      file:
          name: /var/www/html
          state: absent

    - name: Create symlink to mediawiki
      file:
          state: link
          src: "/var/lib/mediawiki"
          dest: /var/www/html
          owner: www-data
          group: www-data
    
    - name: Remove previous install config
      file:
          name: "/var/www/html/wiki/LocalSettings.php"
          state: absent

    - name: Run installation script
      shell: php maintenance/install.php  --dbserver=localhost --dbname=mwdb "--dbuser={{ admin_user }}" "--dbpass={{ admin_pwd }}" "--pass={{ admin_pwd }}" "{{ wiki_name }}" "{{ admin_user }}"
      args:
          chdir: /var/www/html/wiki

    - name: Configure Apache
      apache2_module: name=rewrite state=present

    - name: Modifiy Apache default site
      copy:
          src: 000-default.conf
          dest: /etc/apache2/sites-available/000-default.conf
      
    - name: Restart Apache
      service:
          name: apache2
          state: restarted

