- hosts: all
  remote_user: root
  vars:
      domain_name: ubadevel.envs.subutai.cloud
      admin_user: admin
      admin_pwd:  topsecret
      mw_version: 1.31.0

  tasks: 
    - name: Install required debs
      apt: 
        name: "{{ item }}"
        state: present
      with_items: 
        - php7.0-fpm
        - php7.0-mbstring
        - php7.0-mcrypt
        - php7.0-mysql
        - php7.0-zip
        - php7.0-xml
        - php7.0-gd
        - php7.0-curl
        - python-mysqldb
        - apache2
        - mariadb-server
        - mariadb-client
        - php-apcu
        - php-intl
        - imagemagick
        - inkscape
        - php-gd
        - php-cli
        - git

    - name: Download mediawiki
      get_url:
          url: https://releases.wikimedia.org/mediawiki/1.31/mediawiki-1.31.0.tar.gz
          dest: /tmp/mediawiki.tgz

    - name: Extract mediawiki tar ball
      unarchive:
          src:  /tmp/mediawiki.tgz
          dest: /var/www/html
          remote_src: yes
          owner: www-data
          group: www-data


    - name: Create DataBase User
      mysql_user:
          name: "{{ admin_user }}"
          password: "{{ admin_pwd }}"
          priv: "{{ admin_user }}.*:ALL"
          state: present

    - name: Create DataBase
      mysql_db:
          name: mwdb
          state: present
          encoding: utf8
          login_user: "{{ admin_user}}"
          login_password: "{{ admin_pwd }}"

    - name: Run installation script
      shell: php maintenance/install.php "--server={{ domain_name }}"  --dbserver=localhost --dbname=mwdb "--dbuser={{ admin_user }}" "--dbpass={{ admin_pwd }}"
      args:
          chdir: /var/www-data/html/mediawiki-1.31.0

    - name: Remove index
      file:
          name: /var/www/html/index.html
          state: absent

    - name: Restart Apache
      service:
          name: apache2
          state: restarted

